image: alpine

build:
  stage: build
  script:
  - echo "Building..."
  - cl publish.el
  artifacts:
    path:
    - docs
    - pss

pages:
  after: generate
  stage: deploy
  artifacts:
    path:
    - docs
    - pss
    rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
