# -*- mode:org; coding: utf-8; -*-
#+TITLE: Prady_sh_scripts
#+AUTHOR: Pradyumna Paranjape
#+EMAIL: pradyparanjpe@rediffmail.com
#+LANGUAGE: en
#+OPTIONS: toc:2 num:nil html-postamble:nil ^:nil mathjax:t TeX:t ::t tags:nil *:t skip:t
#+STARTUP: overview
#+PROPERTY: header-args :tangle yes
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+EXPORT_FILE_NAME: ../docs/index.html


* Copyright
  Copyright 2020-2022 Pradyumna Paranjape

* License (GNU GPLv3)
  This file is part of Prady_sh_scripts.
  Prady_sh_scripts is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  Prady_sh_scripts is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with Prady_sh_scripts.  If not, see <https://www.gnu.org/licenses/>.

* Scope
  Files in this project contain regular utilities and aliases for linux (fc35);
  Preferably in POSIX-compliant shell scripts.
